* L2PH CATI ROUND 01
* created by Batmandakh
* las modified by Avraa 
* last modified on Mar 17, 2026

*Note: Move generated raw file to raw folder /$date of Round 1

*-------------------------------------------------------------------------------
* PREAMBLES
*-------------------------------------------------------------------------------
{		
	clear
	set more off
	set excelxlsxlargefile on
	macro drop _all
// 	set processors 8
//	set processors 2
	
	* Set round and user
	********************
	glo LNG ENG 	
	glo R 01
	glo pR 00
	
	scalar user=2 //1=BB, 2=AP, 3=local team
	if (user==1) glo wd "/Users/batmandakh/Library/CloudStorage/GoogleDrive-bt.mandah@gmail.com/My Drive/L2Phl/CATI/Round${R}"
	if (user==2) glo wd  "/Users/avraa/Library/CloudStorage/GoogleDrive-avraltod@gmail.com/My Drive/L2Phl/CATI/Round01/Round 1 - Trailer"
	if (user==3) glo wd "C:\Users\Joy Yangyang\Downloads\TIPON\R1 - Trailer"
	if (user==4) glo wd  "/Users/avraa/iDrive/GitHub/PHL/L2PHL/CATI/Round01/Round 1 - Trailer"   // iDrive/GitHub — @Claude version
			
	cd "$wd" //changing directory 
	
	* Specify import file settings
	********************************
	glo M 11
	glo D 25
	glo Y 2025

	
	glo sheet1 "L2PHL_CATI_R01_Trailer"
	glo version _all_versions_-_False_

	glo excel_file "L2PHL_CATI_R01_Trailer_-_latest_version_-_False_-_2026-01-03-04-59-01"
// 	L2PHL_CATI_R01_Trailer_-_latest_version_-_False_-_2026-01-03-04-59-01
	glo dta_file l2phl
	
	glo date ${Y}${M}${D}	
	glo date_filter "date == mdy($M, $D, $Y)"
	
	* Kobo file
	****************************************************
	glo kobofile "L2PHL_CATI_R01_Trailer"
	
	* Set ado folder and install commands if necessary
	****************************************************
	cap adopath - "$wd/ado/"		
	// making sure are there defined commands
	foreach prog in kobo2stata _gwtmean extremes ///
		winsor2 povdeco apoverty ds3 ///
			clonevar confirmdir unique copydesc dropmiss {
				cap which `prog'
					capture if _rc ssc install `prog' , replace all
	}
	adopath + "$wd/ado/"
	
	* Create folders
	********************
		foreach dir in raw zzz call sample tab fix dta aud {
			confirmdir "${wd}/`dir'/"
			if _rc ~= 0 {
				mkdir "${wd}/`dir'"
			}
			confirmdir "${wd}/`dir'/$date"
			if _rc ~= 0 {
				mkdir "${wd}/`dir'/$date"
			}			
		}

	glo kobo "$wd/kobo"
	glo raw "$wd/raw/$date"
	glo xls "$wd/xls"
	glo ado "$wd/ado"
	glo zzz "$wd/zzz/$date"
	glo call "$wd/call/$date"
	glo fix "$wd/fix/$date"
	glo tab "$wd/tab/$date"
	glo dta "$wd/dta/$date"
	glo aud "$wd/aud/$date"
	glo smpl "$wd/sample/$date"


	* Clean old files
	****************************
	local zzzfiles : dir "${zzz}" files "*.dta"
	local rawfiles : dir "${raw}" files "*.dta"	
		foreach file in `zzzfiles' `rawfiles' {
				di 	"`file'" 						
			*shell rm -r $zzz/`file'
			cap erase "$zzz/`file'"
			cap erase "$raw/`file'"

			}
			

}			
	
	
*------------------------------------------------------------------------------*
* HH-LEVEL - EXCEL TO STATA 
*------------------------------------------------------------------------------*
			
	cap confirm file "$zzz/${sheet1}.dta" 
		if _rc ~= 0 {
		
			import excel "${xls}/$excel_file.xlsx", ///
				describe
			return list
			
			import excel "$wd/xls/$excel_file.xlsx", ///
				sheet(${sheet1}) firstrow clear allstring 
				
			destring , replace 
			
			rename *, lower	
			
			cap drop if hhid == 89012
			
				//UNIQUE HHIDs 
				{
				
				la var hhid "L2PH ID" // Based on the Baseline IDs 
				
				ren _id koboid
				la var koboid "Household ID (Kobo)" // Generated by the KOBO system.
					format koboid %20.0f
						order hhid 
				unique hhid 
					as r(N) == r(unique),r 
					
				bys hhid (z9): g N = _N 
					drop if N>1 & z9 == 2
						cap drop N 
				unique hhid 
					as r(N) == r(unique), r
	
				ren _uuid uuid  		
				as uuid ~= ""
				la var uuid "UUID (Kobo)"
					unique uuid 
						as r(N) == r(unique), r

				ren _submission_time time 
				la var time "Submission time"
					unique time 
					as r(N) == r(unique), r 

				cap as _validation_status ==  . 
					cap drop _validation_status, r	
					
				cap as _notes ==  . 
					cap drop _notes	
				
				as _status ==  "submitted_via_web", r 
					cap drop _status	
					
				as _submitted_by == "tipon"	
					cap drop _submitted_by 
					
				as _tags == .
					cap drop _tags

				ren _index sid
				la var sid "Submission ID (Kobo)"
					unique sid 
						as r(N) == r(unique)
					unique __version__ 
						as r(unique) == 1, r 
							cap drop __version__ */
				}	
			
			
			/// DUPLICATES (keeping the latest submission)
		
			sort hhid time 
			by hhid: keep if _n == 1
			isid hhid

			compress 
			save "$zzz/${sheet1}.dta", replace		
		
		}
		

********************************************************************************
**# (M0) PASSPORT OF QUESTIONNAIRE
********************************************************************************
{ // PASSPORT:
	use "$zzz/${sheet1}.dta", clear
		quietly destring, replace 
	
	
	 //some assertion 
	keep hhid-time_demogs *time* koboid sid uuid time x11-x16
	
	drop oldp* oldage* oldadult* d5a1* ed1* a1* a2* oldd* oldsex*
	drop intro_end you_have_completed_t_nk_you_for_ closing_end oldrespo oldcp oldz10 oldz20 hhhead oldn1
		
			// Submission time & Durations 
			{
				
				la var start "Start Date/Time (string)"
					as start ~= "" 
					split start , parse("T" ".") generate(start_) limit(2)
						cap drop start 
				g double start_date = date(start_1, "YMD") , after(deviceid)
				la var start_date "Start Date"
					format start_date %tdCCYY/NN/DD
				g double start_time = clock(start_1+start_2, "YMDhms"), after(start_date)
				la var start_time "Start Time"
					format start_time %tcCCYY/NN/DD_HH:MM
						cap drop start_1 start_2	
					
				la var end "End Date/Time (string)"
					as end ~= ""
					split end , parse(" " "T" ".") generate(end_) limit(2)
						cap drop end 
				g double end_date = date(end_1, "YMD"), after(start_date)
				la var end_date "End Date"
					format end_date %tdCCYY/NN/DD
				g double end_time = clock(end_1+end_2, "YMDhms"), after(start_time)
				la var end_time "End Time"
					format end_time %tcCCYY/NN/DD_HH:MM:SS
						cap drop end_1 end_2
						
				la var time  "End Date/Time (string)"
					as time ~= ""
					split time , parse(" " "T" ".") generate(sub_) limit(2)
						cap drop time 
				g double date = date(sub_1, "YMD"), after(end_date)
				la var date "Submission Date"
					format date %tdCCYY/NN/DD
				g double time = clock(sub_1+sub_2, "YMDhms"), after(end_time)
				la var time "Submission Time"
					format time %tcCCYY/NN/DD_HH:MM:SS
						cap drop sub_1 sub_2
											
				cap la var nextcall "Start Date/Time (string)"
					cap as nextcall ~= "" if agreement == 1, r 
					cap split nextcall , parse(", ") generate(next_) limit(2)
						cap cap drop nextcall 
				cap g double next_date = date(next_2, "YMD") , after(time)
				cap la var next_date "Next Call Date"
					cap format next_date %tdCCYY/NN/DD
						cap drop next_1	next_2

				
				local timevars time_intro time_educ time_employment time_income

				foreach t of local timevars {

					* Keep milliseconds, remove timezone, replace 'T' with space
					gen str26 `t'_clean = substr(`t',1,23)
					replace `t'_clean = subinstr(`t'_clean,"T"," ",.)
					
					* Convert to Stata datetime (%tc)
					gen double `t'_tc = clock(`t'_clean,"YMDhms")
					format `t'_tc %tcCCYY/NN/DD_HH:MM:SS
					
					drop `t'_clean
				}

				* 1. Demographics duration (time_intro -> time_educ)
				cap drop dur_demogs
				gen double dur_demogs = .
				replace dur_demogs = round((time_educ_tc - time_intro_tc)/60000, 0.001) if !missing(time_intro_tc, time_educ_tc)
				label var dur_demogs "Duration of Demographics (min)"

				* 2. Employment duration (time_educ -> time_employment)
				cap drop dur_emp
				gen double dur_emp = .
				replace dur_emp = round((time_employment_tc - time_educ_tc)/60000, 0.001) if !missing(time_educ_tc, time_employment_tc)
				label var dur_emp "Duration of Employment (min)"

				* 3. Income duration (time_employment -> time_income)
				cap drop dur_inc
				gen double dur_inc = .
				replace dur_inc = round((time_income_tc - time_employment_tc)/60000, 0.001) if !missing(time_employment_tc, time_income_tc)
				label var dur_inc "Duration of Income (min)"
					
					cap drop time_* 	
			}
			
			/// LABELLING FOR HH-LEVEL MODULES 
			
			la lang ENG, copy new
			
			/**************************************************************************
			* 2. NOTE FIELD – hhsize_wrong
			**************************************************************************/
			
			la var hhsize_wrong "Household-ID is NOT in the database. Go back and reenter correct household-ID."
			
			la var sample "Household is in the main sample"
				la def SAMPLE_ENG     ///
					1 "Yes"                 ///
					2 "No", replace
				la val sample SAMPLE_ENG	

			/**************************************************************************
			* 3. TEXT FIELDS – replacement_hhid, z0_first, z0_last
			**************************************************************************/

			la var replacement_hhid "Replacement HHID (original)"
			la var z0_first         "Interviewer first name"
			la var z0_last          "Interviewer last name"


			/**************************************************************************
			* 4. INTERVIEWER ID – int_id
			**************************************************************************/

			destring int_id, replace

			la var int_id "Interviewer ID"

			la def INT_ID_ENG                                      ///
				4017 "4017"                                        ///
				9378 "9378"                                        ///
				9492 "9492"                                        ///
				9408 "9408"                                        ///
				9527 "9527"                                        ///
				9539 "9539"                                        ///
				9514 "9514"                                        ///
				9549 "9549"                                        ///
				9541 "9541"                                        ///
				9550 "9550"                                        ///
				9552 "9552"                                        ///
				9557 "9557"                                        ///
				9559 "9559"                                        ///
				9558 "9558"                                        ///
				9512 "9512"                                        ///
				9442 "9442"                                        ///
				9342 "9342"                                        ///
				9491 "9491"                                        ///
				9486 "9486"                                        ///
				1050 "1050"                                        ///
				1053 "1053"                                        ///
				1733 "1733"                                        ///
				1943 "1943"                                        ///
				6421 "6421"                                        ///
				1997 "1997"                                        ///
				6366 "6366"                                        ///
				6410 "6410"                                        ///
				1013 "1013"                                        ///
				1014 "1014"                                        ///
				6067 "6067"                                        ///
				6300 "6300"                                        ///
				9996 "9996", replace

			la val int_id INT_ID_ENG


			/**************************************************************************
			* 5. DATE OF INTERVIEW – z6
			**************************************************************************/

			gen double z6_date = .
			format z6_date %td
			
			la var z6 "Date of interview"


			/**************************************************************************
			* 6. TIME OF INTERVIEW – z7
			**************************************************************************/

			gen double z7_time = .
			format z7_time %tcHH:MM:SS
			label var z7_time "Time of interview"


			/**************************************************************************
			* 7. CALL ATTEMPT – z8
			**************************************************************************/

			gen byte z8_call = .

			label var z8_call "Call attempt number"

			la def ATTEMPT_ENG                ///
				1 "1st attempt"               ///
				2 "2nd attempt"               ///
				3 "3rd attempt", replace

			la val z8 ATTEMPT_ENG


			/**************************************************************************
			* 8. CALL STATUS – call_status1
			**************************************************************************/

			destring call_status1, replace

			la var call_status1 "Did you speak with someone?"

			la def CALL_STATUS1_ENG     ///
				1 "Yes"                 ///
				2 "No", replace

			la val call_status1 CALL_STATUS1_ENG


			/**************************************************************************
			* 9. PASSPORT INTRO & CONSENT – z16, z17, z9, time_intro, z18, z18_oth, z19
			**************************************************************************/

			* z16: intro text
			la var z16 "Intro: who enumerator is and who they are calling"

			* z17: yes-no (correct respondent?)
			destring z17, replace

			la var z17 "Were you able to speak with the correct respondent?"

			la def YES_NO_ENG            ///
				1 "Yes"                  ///
				2 "No", replace

			la val z17 YES_NO_ENG

			* z9: willingness to participate (agree)
			destring z9, replace

			la var z9 "Willingness to participate (Listening to the Philippines)"

			la def AGREE_ENG             ///
				1 "I agree"              ///
				2 "No, I do not agree", replace

			la val z9 AGREE_ENG


			* z18: reason for refusal (reason_ref)
			destring z18, replace

			la var z18 "Reason for refusal to participate"

			la def REASON_REF_ENG	///
				1  "No time/busy"	///
				2  "Do not want to share my personal information" ///
				3  "No answer/do not know"	///
				4  "Call back at another time (specify date and time)" ///
				96 "Other (specify)", replace

			la val z18 REASON_REF_ENG

			* z18_oth: other text
			la var z18_oth "Reason for refusal: other (specify)"

			* z19: agreement to recording (agree)
			destring z19, replace

			la var z19 "Willing to have interview recorded"

			la def AGREE_ENG             ///
				1 "I agree"              ///
				2 "No, I do not agree", replace

			la val z19 AGREE_ENG


			/**************************************************************************
			* 10. AUDIO, ADDRESS, GEO – backgound_audio, z20, z21, z1–z5
			**************************************************************************/

			* background audio
			la var backgound_audio "Background audio file"

			* z20: still live in same address? (yes-no)
			destring z20, replace

			la var z20 "Do you still live in this address?"

			la def YES_NO_ENG            ///
				1 "Yes"                  ///
				2 "No", replace

			la val z20 YES_NO_ENG

			* z21: new address text
			la var z21 "New address (text)"

			* geo variables – value labels from separate geo do-files
			la var z1 "Region (new address)"
				qui run "$ado/region"
				la val z1 REGION
			
			la var z2 "Province (new address)"
				qui run "$ado/province"
				la val z2 PROV
			
			la var z3 "City/Municipality (new address)"
				qui run "$ado/city"
				la val z3 CITY			
			
			la var z4 "Barangay (new address)"
				qui run "$ado/barangay"
				la val z4 BRN			

			* z5: locale (we have codes here)
			la var z5 "Locale (new address)"

			la def LOCALE_ENG            ///
				1 "Urban"                ///
				2 "Rural", replace

			la val z5 LOCALE_ENG
			
			
			/// RENAMING AND RELABELLING 
			
			// Round number 
			gen round = ${R}
			order round, first
			

			tostring z0_first, replace force
			tostring z0_last, replace force
			gen strL int_name = strtrim(z0_first) + " " + strtrim(z0_last)
			label var int_name "Interviewee full name"
			

			ren z9 agreement
			ren z1 region 
			ren z2 province
			ren z3 city
			ren z4 barangay
			ren z5 locale
			ren z6 date_str
				order date_str, after(date)
			ren z7 time_str
				order time_str, after(time)
			ren z20 address_unchanged
			ren z21 new_address_str
			ren z8 call_attemp
			ren z16 intro 
			ren z17 correct_resp
			ren z18 refusal_reason
			ren z18_oth refusal_reason_oth
			ren z19 interview_record
			
			
			la var int_name "Interview's name"
			la var round "L2PH CATI Round"
			la var hhid "L2PH ID" // Based on the Baseline IDs 
			la var koboid "Household ID (Kobo)" // Generated by the KOBO system.
			la var uuid "UUID (Kobo)" 
			la var sid "Submission ID (Kobo)"
			la var hhsize "Household size (old)"	
			
			
			/// CLOSING 
			
			
			**************************************************************************
			* CLOSING GROUP – group_closing (x11–x20, x20_oth, closing_end, member_talkedto, x15, x16)
			**************************************************************************

			* X11: select_one yes-no
			destring x11, replace

			la var x11 "Another phone number if current number cannot be reached"

			la def YES_NO_ENG            ///
				1 "Yes"                  ///
				2 "No", replace

			la val x11 YES_NO_ENG


			* X12: select_one OLDADULT (whose number?)
			destring x12, replace

			la var x12 "Whose number?"

			* fill OLDADULT list when ready:
			* la def OLDADULT_ENG ...
			* la val x12 OLDADULT_ENG


			* X13_phone: alternative mobile number
			la var x13_phone "Alternative contact number: mobile"

			* X13_landline: alternative landline
			la var x13_landline "Alternative contact number: landline"

			* X14: verify current mobile number (oldcp)
			la var x14 "Verify current mobile number for token (oldcp)"


			* X17: select_one x17 (Prepaid / Postpaid)
			destring x17, replace

			la var x17 "Is this number prepaid or postpaid?"

			la def X17_ENG               ///
				1 "Prepaid"              ///
				2 "Postpaid", replace

			la val x17 X17_ENG


			* X18: prepaid number text (if x17==2)
			la var x18 "Prepaid number for sending small token"


			* X19: select_one confirm (only "Yes")
			destring x19, replace

			la var x19 "Confirm that provided number is prepaid"

			la def CONFIRM_ENG           ///
				1 "Yes", replace

			la val x19 CONFIRM_ENG


			* X20: select_one provider
			destring x20, replace

			la var x20 "Network provider"

			la def PROVIDER_ENG          ///
				1 "Globe"                ///
				2 "TM"                   ///
				3 "GOMO"                 ///
				4 "Smart"                ///
				5 "TNT"                  ///
				7 "Dito"                 ///
				8 "Sun"                  ///
				9 "Others (specify)", replace

			la val x20 PROVIDER_ENG


			* X20_oth: other provider text (if x20==9)
			la var x20_oth "Network provider: other (specify)"


			* member_talkedto: select_one OLDADULT_CP
			destring member_talkedto, replace

			la var member_talkedto "HH member called/interviewed"

			* fill OLDADULT_CP list when ready:
			* la def OLDADULT_CP_ENG ...
			* la val member_talkedto OLDADULT_CP_ENG


			* X15: select_one Callrem (result of interview)
			destring x15, replace

			la var x15 "Result of the interview"

			la def CALLREM_ENG                                               ///
				1  "Complete"                                                ///
				2  "Partially complete, no more callback"                    ///
				3  "Partially complete, scheduled another call"              ///
				4  "Not yet started, with scheduled callback"                ///
				5  "Refused"                                                 ///
				6  "Nobody answering / Just ringing"                         ///
				7  "Number does not exist / Not ringing"                     ///
				8  "Phone turned off / Not in service"                       ///
				9  "Don't know the household"                                ///
				10 "Reference person can't connect to the household / owner of the number", replace

			la val x15 CALLREM_ENG


			* X16: call remarks
			la var x16 "Call remarks"		
			
			/// RENAMING AND RELABELLING
			
			ren date subm_date 
			ren time subm_time
			
			ren member_talkedto resp_fmid
			la var resp_fmid "Please, identify the respondent"
			
			drop z6_date-int_name
			
				la lang ${LNG}
				compress 
				save "$raw/${dta_file}_${date}_M00_passport.dta", replace

}
*------------------------------------------------------------------------------*
			
		

	
********************************************************************************
**# (M1) ROSTER (TRAILER)
********************************************************************************
{ //ROSTER: 

	import excel "$wd/xls/$excel_file.xlsx", sheet("old_") firstrow clear
		quietly destring, replace 	
	
	ren *, lower
	
	// FILTERING
	
	keep if fmidreaskdem == 1
	drop fmidreaskdem
	
	//UNIQUE HHID 
	{

	as old_hhid ~=. 
		ren old_hhid hhid 
		la var hhid "L2PHL ID"
	ren old_fmid fmid
		la var fmid "Family member ID"
	as fmidfieldname ~= ""
		cap drop fmidfieldname
	as fmidname ~= "" , r 
		*ren fmidname name 
	gen name = fmidname if fmidname ~= ""
	la var name "Name"

	as fmidage ~= . , r 
		*ren fmidage age
	gen age = fmidage if fmidage ~= .
	la var age "Age"
	
	as fmidpermanent ~= . , r
		ren fmidpermanent permanent
	
	drop *field*
			
	ren _submission_* * 	
	
		{
		as _index ~= . 
			ren _index iid
			la var iid "Individual ID (Kobo)" 
				cap drop iid 
		as _parent_table_name == "$sheet1"
			cap drop _parent_table_name
		ren _parent_index sid
			la var sid "Submission ID (Kobo)" 
			as sid ~= .
		ren _id koboid
			la var koboid "Household ID (Kobo)" // Generated by the KOBO system.
			format koboid %20.0f
		ren _uuid uuid  		
			as uuid ~= ""
			la var uuid "UUID (Kobo)"	
		ren _submission_time time 
			la var time "Submission time"
				as time ~= ""
				split time , parse(" " "T" ".") generate(sub_) limit(2)
					cap drop time 
			g double subm_date = date(sub_1, "YMD"), after(uuid)
			la var subm_date "Submission Date"
				format subm_date %tdCCYY/NN/DD
			g double subm_time = clock(sub_1+sub_2, "YMDhms"), after(subm_date)
			la var subm_time "Submission Time"
				format subm_time %tcCCYY/NN/DD_HH:MM:SS
					cap drop sub_1 sub_2	
			
		cap as _validation_status ==  .  
			cap drop _validation_status	
		as _notes ==  . 
			cap drop _notes	
		as _status ==  "submitted_via_web", r
			cap drop _status	
		as _submitted_by == "tipon"	
			cap drop _submitted_by 
		as _tags == .
			cap drop _tags
			
			cap drop _submission_* 
			cap drop __version__
			
			bys koboid fmid sid hhid uuid subm_date subm_time: g N = _N
					as N == 1
						cap drop N

			unique koboid fmid sid hhid uuid subm_date subm_time 
				if `r(N)' ~= `r(unique)' {
					bys koboid fmid sid hhid uuid subm_date subm_time : g n = _n 
						bro if n > 1 
					as n == 1, r
						drop if n > 1 
							cap drop n
				}

				unique koboid fmid sid hhid uuid subm_date subm_time 
					as r(N) == r(unique)
		}
	}

	drop if ///
			name == "" & ///
			age == . 
	
	
	/// TEMPORARY 
	
	replace d5a = "1" if d5a == "2 4" & hhid == 105565 & fmid == 2
	replace d5a = "1" if d5a == "4 1" & hhid == 100105 & fmid == 2
	replace d5a = "1" if d5a == "4 1" & hhid == 83024 & fmid == 2


	//ENGLISH 
	{
		
	la lang ENG, copy new

	/**************************************************************************
	* D5a – D28: ROSTER CORRECTION / MOVED-OUT MEMBERS
	**************************************************************************/

	*------------------------------------------------------------------------------
	* D5a – Did member live in the household last 30 days?
	*------------------------------------------------------------------------------
	destring d5a, replace

	la var d5a "D5a. Did this member live in the household in the last 30 days?"

	la def D5A_ENG ///
		1 "Yes" ///
		2 "No" ///
		3 "Name is recorded incorrectly" ///
		4 "Age is recorded incorrectly", replace

	la val d5a D5A_ENG

		* ASSERTIONS
		* d5a ~= . always
		as d5a ~= . 
		* no extra conditions


	*------------------------------------------------------------------------------
	* D25 – Reason why member left household
	*------------------------------------------------------------------------------
	destring d25, replace

	la var d25 "D25. Please tell me why the member left the household"

	la def D25_ENG ///
		1  "Moved out" ///
		2  "Married and moved out" ///
		3  "Died" ///
		96 "Other (specify)", replace

	la val d25 D25_ENG	

		* ASSERTIONS
		* must be filled ONLY when d5a == 2 (not living in household)
		as d25 ~= . if d5a == 2
		as d25 == . if d5a == 1 | d5a == 3 | d5a == 4


	*------------------------------------------------------------------------------
	* D25_oth – Other reason
	*------------------------------------------------------------------------------
	la var d25_oth "D25. Other reason why member left (specify)"

		* ASSERTIONS
		* only required when d25 == 96
		as d25_oth ~= "" if d25 == 96
		as d25_oth == "" if d25 != 96


	*------------------------------------------------------------------------------
	* D26_1 – Country where member moved to
	*------------------------------------------------------------------------------
	la var d26_1 "D26_1. Country where member moved"
			qui run "$ado/country"
			la val d26_1 COUNTRY
	

		* ASSERTIONS
		* only shown if d25 == 1 or d25 == 2
		as d26_1 ~= . if d25 == 1 | d25 == 2
		as d26_1 == . if d25 != 1 & d25 != 2, r



	*------------------------------------------------------------------------------
	* D26_2 – Province where member moved (only if country == 1)
	*------------------------------------------------------------------------------
	la var d26_2 "D26_2. Province where member moved"
			qui run "$ado/province"
			la val d26_2 PROV

		* ASSERTIONS
		as d26_2 ~= . if d26_1 == 1
		as d26_2 == . if d26_1 != 1
		


	*------------------------------------------------------------------------------
	* D26_3 – City/Municipality where member moved
	*------------------------------------------------------------------------------
	la var d26_3 "D26_3. City/Municipality where member moved"
			qui run "$ado/city"
			la val d26_3 CITY	
	

		* ASSERTIONS
		as d26_3 ~= . if d26_1 == 1
		as d26_3 == . if d26_1 != 1


	*------------------------------------------------------------------------------
	* D27 – Correct name
	*------------------------------------------------------------------------------
	la var d27 "D27. Correct name of the member"

		* ASSERTIONS
		* required ONLY when d5a == 3 (name incorrect)
		cap as d27 ~= "" if d5a == 3
		cap as d27 == "" if d5a == 1 | d5a == 2 | d5a == 4


	*------------------------------------------------------------------------------
	* D28 – Correct age
	*------------------------------------------------------------------------------
	destring d28, replace

	la var d28 "D28. Correct age of the member"

		* ASSERTIONS
		* required ONLY when d5a == 4 (age incorrect)
		cap as d28 ~= . if d5a == 4
		as d28 == . if d5a == 1 | d5a == 2 | d5a == 3	
			
	}
	
	
	ren fmidname name_old
	ren fmidage  age_old
	ren fmidsex  gender

	ren d5a      isfmid
	ren d25      member_leftreason
	ren d25_oth  member_leftreason_other
	ren d27      correct_name
	ren d28      correct_age
	ren d26_1    country_moved
 	ren d26_2	 prov_moved
	ren d26_3	 city_moved
	
	
	replace name = trim(itrim(proper(name))) 
	
	tostring correct_name , replace
	replace correct_name = "" if correct_name == "."
	
	replace correct_name = trim(itrim(proper(correct_name))) 
	replace name = correct_name if isfmid == 3 & correct_name ~= ""
	
	replace age = correct_age if isfmid == 4 & correct_age ~= .
		
	
	/// ORDERING 
	
	order name, after(name_old)
	order age gender, after(age_old)
	
	cap drop fmidsexlabel name_old age_old correct* 
	
	sort hhid
	
	la lang ${LNG}
	compress 
	save "$zzz/roster_trailer.dta", replace
	
	
}
*------------------------------------------------------------------------------*

{ 
	///MERGE 
	use "$zzz/roster_trailer.dta", clear

	merge m:1 hhid using "$raw/${dta_file}_${date}_M00_passport.dta", ///
		keepusing(dur_demogs hhsize round)

	tab _merge
	keep if _merge == 3
	drop _merge

	drop sid koboid uuid
	
	ren dur_demogs dur_rr
	la var gender "Gender of household member"
	la var child_check "Child indicator (5-17 years old)"
	
	order round hhid fmid hhsize, first
	order dur_rr, b(subm_date)
	
	compress 
	save "${raw}/roster_trailer.dta", replace
}
	
	
	
	
********************************************************************************
**# (M4) EMPLOYMENT (TRAILER)
********************************************************************************
{ 

	//EMPLOYMENT: 
	 import excel "$wd/xls/$excel_file.xlsx", sheet("employ_") firstrow clear
		 quietly destring, replace 
	
	
		 
	ren *, lower	 
	ren _submission_* * 	
	
	
	drop fmida1-fmidfieldreaskemploy
	drop p7d_r1
	
	ren a21_2 a21_own

	
	drop *field*
	
	//UNIQUE HHID 
	{

	as employ_old_hhid ~=. 
		ren employ_old_hhid hhid 
		la var hhid "L2PH ID"
	
	ren employ_old_fmid fmid 
		la var fmid "Family member ID"
		
	ren employ_fmidname name 
		la var name "Family member name"
	
	drop if name == "" 
	keep if fmidreaskemploy == 1 // filtering
	drop fmidreaskemploy
	
		
		{
		as _index ~= . 
			ren _index iid
			la var iid "Individual ID (Kobo)" 
				cap drop iid 
		as _parent_table_name == "$sheet1"
			cap drop _parent_table_name
		ren _parent_index sid
			la var sid "Submission ID (Kobo)" 
			as sid ~= .
		ren _id koboid
			la var koboid "Household ID (Kobo)" // Generated by the KOBO system.
			format koboid %20.0f
		ren _uuid uuid  		
			as uuid ~= ""
			la var uuid "UUID (Kobo)"
		ren _submission_time time 
			la var time "Submission time"
				as time ~= ""
				split time , parse(" " "T" ".") generate(sub_) limit(2)
					cap drop time 
			g double subm_date = date(sub_1, "YMD"), after(uuid)
			la var subm_date "Submission Date"
				format subm_date %tdCCYY/NN/DD
			g double subm_time = clock(sub_1+sub_2, "YMDhms"), after(subm_date)
			la var subm_time "Submission Time"
				format subm_time %tcCCYY/NN/DD_HH:MM:SS
					cap drop sub_1 sub_2
			
		cap as _validation_status ==  . 
			cap drop _validation_status	
		as _notes ==  . 
			cap drop _notes	
		as _status ==  "submitted_via_web", r 
			cap drop _status	
		as _submitted_by == "tipon"	
			cap drop _submitted_by 
		as _tags == .
			cap drop _tags
			
			cap drop _submission_* 
			cap drop __version__ 
			
			bys koboid fmid sid hhid uuid subm_date subm_time: g N = _N
					as N == 1, r 
						cap drop N

			unique koboid fmid sid hhid uuid subm_date subm_time 
				if `r(N)' ~= `r(unique)' {
					bys koboid fmid sid hhid uuid subm_date subm_time : g n = _n 
						bro if n > 1 
					as n == 1, r
						drop if n > 1 
							cap drop n
				}

				unique koboid fmid sid hhid uuid subm_date subm_time 
					as r(N) == r(unique)	
		}
	}
	
	
	//ENGLISH 
	{
		
	la lang ENG, copy new

	
	**************************************************************************
	* EMPLOYMENT MODULE – A24–A23
	**************************************************************************

	*---------------------------------------------------------
	* A24: job/hours change for those working last month
	*---------------------------------------------------------
	destring a24, replace

	la var a24 "A24. Last month, employ_fmidname was working as fmidA4 in fmidA5label. Was there a change in his/her job or in the number of hours he/she was working per week?"

	la def A24_ENG ///
		1 "Yes, have a new job" ///
		2 "Yes, don't have a job now" ///
		4 "No change, same job", replace

	la val a24 A24_ENG


	*---------------------------------------------------------
	* A27: work status change for those not working last month
	*---------------------------------------------------------
	destring a27, replace

	la var a27 "A27. Last month, employ_fmidname was not working. Was there a change in his/her work status?"

	la def A27_ENG ///
		1 "Yes, have a job now" ///
		2 "No change, no job", replace

	la val a27 A27_ENG


	*---------------------------------------------------------
	* A25: note text
	*---------------------------------------------------------
	la var a25 "A25. Confirm other employment details of employ_fmidname are still the same"


	*---------------------------------------------------------
	* A25_oldA6: CLASS OF WORKER still same? (yes-no)
	*---------------------------------------------------------
	destring a25_olda6, replace

	la var a25_olda6 "A25_oldA6. CLASS OF WORKER - fmidA6label still the same?"

	la def YES_NO_ENG ///
		1 "Yes" ///
		2 "No", replace

	la val a25_olda6 YES_NO_ENG


	*---------------------------------------------------------
	* A25_oldA8A9: GIG / PLATFORM still same? (yes-no)
	*---------------------------------------------------------
	destring a25_olda8a9, replace

	la var a25_olda8a9 "A25_oldA8&A9. INCIDENCE OF GIG WORK / DIGITAL PLATFORM - fmidA8label - fmidA9label still the same?"

	la def YES_NO_ENG ///
		1 "Yes" ///
		2 "No", replace

	la val a25_olda8a9 YES_NO_ENG


	*---------------------------------------------------------
	* A25_oldA10: usual days per week still same? (yes-no)
	*---------------------------------------------------------
	destring a25_olda10, replace

	la var a25_olda10 "A25_oldA10. Usual number of days worked per week - fmidA10 still the same?"

	la def YES_NO_ENG ///
		1 "Yes" ///
		2 "No", replace

	la val a25_olda10 YES_NO_ENG


	*---------------------------------------------------------
	* A25_oldA11: usual hours per week still same? (yes-no)
	*---------------------------------------------------------
	destring a25_olda11, replace

	la var a25_olda11 "A25_oldA11. Usual number of hours worked per week - fmidA11 still the same?"

	la def YES_NO_ENG ///
		1 "Yes" ///
		2 "No", replace

	la val a25_olda11 YES_NO_ENG


	*---------------------------------------------------------
	* A1: did any work in past week? (yes-no)
	*---------------------------------------------------------
	destring a1, replace

	la var a1 "A1. Did employ_fmidname do any work for at least one hour during the past week?"

	la def YES_NO_ENG ///
		1 "Yes" ///
		2 "No", replace

	la val a1 YES_NO_ENG


	*---------------------------------------------------------
	* A26: labor market status in past week
	*---------------------------------------------------------
	destring a26, replace

	la var a26 "A26. Which of these is applicable to employ_fmidname?"

	la def A26_ENG ///
		1 "Have a job or business during the past week" ///
		2 "Looking for a job" ///
		3 "Looking for more work" ///
		4 "None of the above", replace

	la val a26 A26_ENG


	*---------------------------------------------------------
	* A3: reason did not try to find job (single choice)
	*---------------------------------------------------------
	destring a3, replace

	la var a3 "A3. Main reason why you/employ_fmidname did not try to find a paid job or start a business in the past week"

	la def A3_ENG ///
		1  "Applied/searched and waiting to hear back" ///
		2  "Awaiting recall from a previous job" ///
		3  "Waiting for the season to start" ///
		4  "Will start new job or business soon" ///
		5  "Tired of looking for jobs, no jobs in area" ///
		6  "No jobs matching skills, lacks experience" ///
		7  "Too young or too old" ///
		8  "In studies, training" ///
		9  "Family / household responsibilities" ///
		10 "In agriculture / fishing for family use" ///
		11 "Own disability, injury, illness" ///
		12 "Retired, pensioner, other sources of income" ///
		21 "Operations of my job stopped" ///
		24 "Lack of Financial Capacity" ///
		33 "Lazy" ///
		34 "Being bullied" ///
		36 "Serving in the barangay" ///
		38 "Still lacking requirements" ///
		39 "Too much rain " ///
		40 "Focused on religious duties or obligations" ///
		43 "In prison" ///
		26 "Pregnant" ///
		27 "Currently on vacation" ///
		29 "Deceased" ///
		99 "None" ///
		96 "Other (specify)", replace

	la val a3 A3_ENG

	la var a3_oth "A3. Other reason for not looking for job (specify)"


	*---------------------------------------------------------
	* A4: occupation (text)
	*---------------------------------------------------------

	destring a4, replace
	qui run "$ado/M04_a4"
	la val a4 A4_ENG
	
	ren a4_oth_r1 a4_oth

	*---------------------------------------------------------
	* A5: industry (single choice)
	*---------------------------------------------------------
	destring a5, replace

	la var a5 "A5. Industry in which employ_fmidname worked during the past week"

	la def A5_ENG ///
		1 "Agriculture, Forestry, and Fishing" ///
		2 "Wholesale and retail trade; repair of motor  vehicles and motorcycles" ///
		3 "Accommodation and food service activities" ///
		4 "Administrative and support service activities" ///
		5 "Professional, Scientific and Technical Activities" ///
		6 "Education" ///
		7 "Water Supply; Sewerage, Waste Management and Remediation Activities" ///
		8 "Other Service Activities" ///
		9 "Construction" ///
		10 "Transportation and Storage" ///
		12 "Arts, Entertainment and Recreation" ///
		18 "Real Estate Activities" ///
		19 "Manufacturing" ///
		20 "Information and Communication" ///
		23 "Financial and Insurance Activities" ///
		26 "Public Administration and Defense; Compulsory Social Security" ///
		27 "Mining and Quarrying" ///
		37 "Human Health and Social Work Activities" ///
		56 "Administrative and Support Service Activities" ///
		65 "Private company" ///
		66 "Personal services" ///
		96 "Other, specify industry:", replace

	la val a5 A5_ENG

	la var a5_oth "A5. Other industry (specify)"


	*---------------------------------------------------------
	* A6: class of worker (single choice)
	*---------------------------------------------------------
	destring a6, replace

	la var a6 "A6. Class of worker of employ_fmidname during the past month"

	la def A6_ENG ///
		1 "Worked for private household" ///
		2 "Worked for private establishment" ///
		3 "Worked for government/government corporation" ///
		4 "Self-employed without any paid employee" ///
		5 "Employer in own business or family-operated farm" ///
		6 "Worked with pay in own business or family-operated farm" ///
		7 "Worked without pay in own business or family-operated farm" ///
		9 "None", replace

	la val a6 A6_ENG


	*---------------------------------------------------------
	* A7: intended use of farming/animal/fishing products
	*---------------------------------------------------------
	destring a7, replace

	la var a7 "A7. Are the products employ_fmidname works on intended…?"

	la def A7_ENG ///
		1  "Only for sale" ///
		2  "Mainly for sale" ///
		3  "Mainly for family use" ///
		4  "Only for family use" ///
		97 "Cannot say", replace

	la val a7 A7_ENG


	*---------------------------------------------------------
	* A8: is work a gig work? (yes-no-dk)
	*---------------------------------------------------------
	destring a8, replace

	la var a8 "A8. Is employ_fmidname's work a gig work?"

	la def YES_NO_DK_ENG ///
		1 "Yes" ///
		2 "No" ///
		99 "Don't know", replace

	la val a8 YES_NO_DK_ENG


	*---------------------------------------------------------
	* A9: type of digital platform
	*---------------------------------------------------------
	destring a9, replace

	la var a9 "A9. Digital platform of employ_fmidname's work"

	la def A9_ENG ///
		1  "ONLINE WEB-BASED PLATFORM" ///
		2  "LOCATION-BASED PLATFORM" ///
		99 "Don't know", replace

	la val a9 A9_ENG


	*---------------------------------------------------------
	* A10: usual days per week (integer)
	*---------------------------------------------------------
	destring a10, replace

	la var a10 "A10. How many days does employ_fmidname usually work in a week?"


	*---------------------------------------------------------
	* A11: usual hours per week (integer)
	*---------------------------------------------------------
	destring a11, replace

	la var a11 "A11. How many hours does employ_fmidname usually work in a week?"


	*---------------------------------------------------------
	* A16: contract type
	*---------------------------------------------------------
	destring a16, replace

	la var a16 "A16. Written contract or oral agreement?"

	la def A16_ENG ///
		1  "Yes, written contract" ///
		2  "Yes, verbal agreement" ///
		3  "No contract" ///
		99 "Don't know", replace

	la val a16 A16_ENG


	*---------------------------------------------------------
	* A17: total length of current contract
	*---------------------------------------------------------
	destring a17, replace

	la var a17 "A17. Total length of current contract or agreement"

	la def A17_ENG ///
		1  "Less than one month" ///
		2  "1 to less than 6 months" ///
		3  "6 to less than 12 months" ///
		4  "One year or more" ///
		5  "No specified duration" ///
		99 "Don't know", replace

	la val a17 A17_ENG


	*---------------------------------------------------------
	* A18: employer pays contributions? (yes-no-dk)
	*---------------------------------------------------------
	destring a18, replace

	la var a18 "A18. Employer pays contributions to Pension/Unemployment Insurance?"

	la def YES_NO_DK_ENG ///
		1 "Yes" ///
		2 "No" ///
		99 "Don't know", replace

	la val a18 YES_NO_DK_ENG


	/**************************************************************************
	* A19: EMPLOYMENT BENEFITS (SELECT_MULTIPLE)
	**************************************************************************/
	
	la def EMPLOYMENT_BENEFIS_ENG ///
		1 "Workplace pension plan" ///
		2 "Paid leave (vacation/annual, sick, maternity/paternity)" ///
		3 "SSS/GSIS" ///
		4 "PhilHealth" ///
		5 "Private health insurance/HMO" ///
		11 "Life Plan" ///
		12 "Pag-ibig" ///
		13 "Incentives" ///
		14 "Tips" ///
		15 "Crop insurance" ///
		16 "Senior Citizen benefit" ///
		17 "Local government project" ///
		96 "Do not use this codes, (STG codes for others) for recode" ///
		7 "None of the above", replace

	split a19, gen(a19_)
	local nvars = r(nvars)
	forvalues i = 1/`nvars' {
		destring a19_`i', replace
		label variable a19_`i' "Employment benefits `i'" 
		label val a19_`i' EMPLOYMENT_BENEFIS_ENG
	}

	order a19_1-a19_4, after(a19)

	*---------------------------------------------------------
	* A20: for whom did employ_fmidname work?
	*---------------------------------------------------------
	destring a20, replace

	la var a20 "A20. For whom did employ_fmidname work?"

	la def A20_ENG ///
		1 "A single client" ///
		2 "Multiple clients" ///
		3 "Another company or person subcontracting tasks, projects, or clients" ///
		4 "An agency, broker or other type of intermediary" ///
		5 "A website or app that matches the business with clients or potential clients", replace

	la val a20 A20_ENG


	/**************************************************************************
	* A21: TRANSPORT MODE TO/FROM WORK (SELECT_MULTIPLE)
	**************************************************************************/
	
	la def MODE_OF_TRANSPORTATION_ENG ///
		1 "By foot" ///
		2 "Used own vehicle - car, motorcycle, tricycle (specify)" ///
		15 "Van" ///
		3 "Bicycle" ///
		4 "For hire Motorcycle/Tricycle" ///
		5 "Jeepney/Bus" ///
		6 "TNVS Car (like Grab)/Taxi" ///
		7 "Boat" ///
		8 "Airplane" ///
		9 "Horse or water buffalo " ///
		96 "Others (specify)" ///
		31 "Train" ///
		32 "Truck" ///
		33 "Company service" ///
		34 "Sports Utility Vehicle/ SUV" ///
		35 "Pick Up Truck" ///
		36 "Government service" ///
		37 "Tractor" ///
		97 "Work from Home" ///
		98 "Refused to answer" ///
		99 "Don't know", replace

	split a21, gen(a21_)
	local nvars = r(nvars)
	forvalues i = 1/`nvars' {
		destring a21_`i', replace
		label variable a21_`i' "Mode of transportation to work `i'" 
		label val a21_`i' MODE_OF_TRANSPORTATION_ENG
	}

	tostring a21_own, replace
	cap la var a21_own "A21. Used own vehicle - specify (car, motorcycle, tricycle)"
	cap la var a21_oth     "A21. Other transport (specify)"
	
	
	order a21_1-a21_2, after(a21)
	
	
	*---------------------------------------------------------
	* A22: travel time to workplace (minutes)
	*---------------------------------------------------------
	destring a22, replace

	la var a22 "A22. Travel time from home to workplace (minutes)"


	*---------------------------------------------------------
	* A23: usual transport cost to/from work
	*---------------------------------------------------------
	destring a23, replace

	la var a23 "A23. Usual transport cost to and from work"
		
		
		
	

	
		
	}
	

	
	
	/// RENAME AND RELABEL

	
	
	
	
	

	/// CONSISTENT WITH BASELINE 

	
	
	
	
	
	
	/// STATUS FOR NEW MEMBER 
	
	cap drop if hhid == 89012
	
	la lang ${LNG}
	save "$zzz/employ_trailer.dta", replace
	
}
*------------------------------------------------------------------------------*

	
{ 
	///MERGE 
	use "$zzz/employ_trailer.dta", clear

	merge m:1 hhid using "$raw/${dta_file}_${date}_M00_passport.dta", ///
		keepusing(dur_emp round)

	tab _merge
	keep if _merge == 3
	drop _merge
	
	drop round
	drop employ_fmidage sid koboid uuid
	
	order hhid fmid, first
	order dur_emp, b(subm_date)
	
	compress 
	save "${raw}/employ_trailer.dta", replace
}
	

********************************************************************************
**# (M5) INCOME (TRAILER)
********************************************************************************
{ 

	//INCOME: 
	 import excel "$wd/xls/$excel_file.xlsx", sheet("income_") firstrow clear
		 quietly destring, replace 
		 
	ren *, lower	 
	ren _submission_* * 	
		
	drop *field* 
	
	keep if fmidreaskincome == 1
	drop fmidreaskincome
	///drop if fmida27 == . 
	
	
	local incvars ia3_a ia3_b ia3_c ia3_d ia3_e ia3_f ia6_a ia6_b ia6_c ia6_d ia6_e ia6_f
	
	foreach v of local incvars {
		replace `v' = 0 if `v' == . 
	}
	
	
	
	//UNIQUE HHID 
	{

	as income_old_hhid ~=. 
		ren income_old_hhid hhid 
		la var hhid "L2PH ID"
	
	ren income_old_fmid fmid 
		la var fmid "Family member ID"
		
	ren income_fmidname name 
		la var name "Family member name"
	
	drop if name == "" 
	drop if income_fmida1 == .
		
		{
		as _index ~= . 
			ren _index iid
			la var iid "Individual ID (Kobo)" 
				cap drop iid 
		as _parent_table_name == "$sheet1"
			cap drop _parent_table_name
		ren _parent_index sid
			la var sid "Submission ID (Kobo)" 
			as sid ~= .
		ren _id koboid
			la var koboid "Household ID (Kobo)" // Generated by the KOBO system.
			format koboid %20.0f
		ren _uuid uuid  		
			as uuid ~= ""
			la var uuid "UUID (Kobo)"
		ren _submission_time time 
			la var time "Submission time"
				as time ~= ""
				split time , parse(" " "T" ".") generate(sub_) limit(2)
					cap drop time 
			g double subm_date = date(sub_1, "YMD"), after(uuid)
			la var subm_date "Submission Date"
				format subm_date %tdCCYY/NN/DD
			g double subm_time = clock(sub_1+sub_2, "YMDhms"), after(subm_date)
			la var subm_time "Submission Time"
				format subm_time %tcCCYY/NN/DD_HH:MM:SS
					cap drop sub_1 sub_2	
			
		cap as _validation_status ==  . 
			cap drop _validation_status	
		as _notes ==  . 
			cap drop _notes	
		as _status ==  "submitted_via_web", r 
			cap drop _status	
		as _submitted_by == "tipon"	
			cap drop _submitted_by 
		as _tags == .
			cap drop _tags
			
			cap drop _submission_* 
			cap drop __version__ 
			
			bys koboid fmid sid hhid uuid subm_date subm_time: g N = _N
					as N == 1, r 
						cap drop N

			unique koboid fmid sid hhid uuid subm_date subm_time 
				if `r(N)' ~= `r(unique)' {
					bys koboid fmid sid hhid uuid subm_date subm_time : g n = _n 
						bro if n > 1 
					as n == 1, r
						drop if n > 1 
							cap drop n
				}

				unique koboid fmid sid hhid uuid subm_date subm_time 
					as r(N) == r(unique)	
		}
	}
	
	
	
	
	
	
	
	
	//ENGLISH 
	{
		
	la lang ENG, copy new

		
	* income_fmidA1 is the baseline A1 (employment status), pulled from EDUC_WORK
	destring income_fmida1, replace

	la var income_fmida1 "Baseline employment status (A1) for income module routing"

	la def INCOME_FMIDA1_ENG ///
		1 "Worked at baseline" ///
		2 "Not working at baseline", replace

	la val income_fmida1 INCOME_FMIDA1_ENG	
	
	
	/**************************************************************************
	* INCOME FROM EMPLOYMENT – IA2–IA7 
	**************************************************************************/

	*---------------------------------------------------------
	* IA2: regular salaries and wages (yes-no)
	*---------------------------------------------------------
	destring ia2, replace

	la var ia2 "IA2. Regular salaries and wages (cash & in-kind) in Sept–Oct 2025?"

	la def YES_NO_ENG ///
		1 "Yes" ///
		2 "No", replace

	la val ia2 YES_NO_ENG

		
	* IA3 note
	la var n_ia3 "IA3. Intro note for detailed earnings amounts"

	*---------------------------------------------------------
	* IA3_A–IA3_F: detailed components of earnings (integers)
	*---------------------------------------------------------
	destring ia3_a ia3_b ia3_c ia3_d ia3_e ia3_f, replace

	la var ia3_a "IA3_A. Cash earnings: basic salaries and wages"
	la var ia3_b "IA3_B. Cash earnings: other (bonus, commission, gratuities, honoraria)"

	la var ia3_c "IA3_C. In-kind: basic salaries and wages"
	la var ia3_d "IA3_D. In-kind: housing"
	la var ia3_e "IA3_E. In-kind: food"
	la var ia3_f "IA3_F. In-kind: other (transport, education, clothing, other goods)"


	*---------------------------------------------------------
	* TOTAL_CASH_EARNINGS + confirmation
	*---------------------------------------------------------
	cap la var total_cash_earnings "Total cash earnings (IA3_A + IA3_B)"

	cap destring total_cash_earnings_cf, replace

	cap la var total_cash_earnings_cf "Confirm total cash earnings amount"

	cap la def CONFIRM_ENG ///
		1 "Yes", replace

	cap la val total_cash_earnings_cf CONFIRM_ENG



	*---------------------------------------------------------
	* TOTAL_EARNINGS_INKIND + confirmation
	*---------------------------------------------------------
	la var total_earnings_inkind "Total earnings in-kind (IA3_C–IA3_F)"

	destring total_earnings_inkind_cf, replace

	la var total_earnings_inkind_cf "Confirm total earnings in-kind amount"

	la def CONFIRM_ENG ///
		1 "Yes", replace

	la val total_earnings_inkind_cf CONFIRM_ENG



	*---------------------------------------------------------
	* IA3_TOTAL_INCOME + zero-income note
	*---------------------------------------------------------
	la var ia3_total_income "Total income from regular employment (cash + in-kind)"

	la var ia3_total_income_zero "Check: member is working, but IA3 total income recorded as zero"



	*---------------------------------------------------------
	* IA5: seasonal/occasional wages (yes-no)
	*---------------------------------------------------------
	destring ia5, replace

	la var ia5 "IA5. Received salaries/wages as seasonal/occasional worker in Sept–Oct 2025?"

	la def YES_NO_ENG ///
		1 "Yes" ///
		2 "No", replace

	la val ia5 YES_NO_ENG
		


	* IA6_A–IA6_F: seasonal/gig detailed earnings
	destring ia6_a ia6_b ia6_c ia6_d ia6_e ia6_f, replace

	la var ia6_a "IA6_A. Cash earnings (seasonal/gig): basic salaries and wages"
	la var ia6_b "IA6_B. Cash earnings (seasonal/gig): other (bonus, commission, gratuities, honoraria)"

	la var ia6_c "IA6_C. In-kind (seasonal/gig): basic salaries and wages"
	la var ia6_d "IA6_D. In-kind (seasonal/gig): housing"
	la var ia6_e "IA6_E. In-kind (seasonal/gig): food"
	la var ia6_f "IA6_F. In-kind (seasonal/gig): other (transport, education, clothing, other goods)"

	*---------------------------------------------------------
	* TOTAL_CASH_EARNINGS_GIG + confirmation
	*---------------------------------------------------------
	la var total_cash_earnings_gig "Total cash earnings from seasonal/gig work"

	destring total_cash_earnings_gig_cf, replace

	la var total_cash_earnings_gig_cf "Confirm total cash earnings from seasonal/gig work"

	la def CONFIRM_ENG ///
		1 "Yes", replace

	la val total_cash_earnings_gig_cf CONFIRM_ENG

	*---------------------------------------------------------
	* TOTAL_EARNINGS_INKIND_GIG + confirmation
	*---------------------------------------------------------
	la var total_earnings_inkind_gig "Total in-kind earnings from seasonal/gig work"

	destring total_earnings_inkind_gig_cf, replace

	la var total_earnings_inkind_gig_cf "Confirm total in-kind earnings from seasonal/gig work"

	la def CONFIRM_ENG ///
		1 "Yes", replace

	la val total_earnings_inkind_gig_cf CONFIRM_ENG

	*---------------------------------------------------------
	* IA5_TOTAL_INCOME + zero-income note
	*---------------------------------------------------------
	la var ia5_total_income "Total income from seasonal/occasional work (cash + in-kind)"

	la var ia5_total_income_zero "Check: IA5=1 but IA5 total income recorded as zero"


	*---------------------------------------------------------
	* TOTAL_INCOME: combined income from regular + seasonal work
	*---------------------------------------------------------
	la var total_income "Total income from all employment sources (regular + seasonal/gig)"


	*---------------------------------------------------------
	* IA7: how much of TOTAL_INCOME is from gig work?
	*---------------------------------------------------------
	destring ia7, replace

	la var ia7 "IA7. Of TOTAL_INCOME, how much is from gig work?"
	
	
	
	
	/// CALCULATING TOTALS 
	
	
	* FIRST DROPPING ALL TOTALS FROM KOBO 
	
		drop total_cash_earnings total_cash_earnings_cf total_earnings_inkind total_earnings_inkind_cf ia3_total_income ia3_total_income_zero total_cash_earnings_gig total_cash_earnings_gig_cf total_earnings_inkind_gig total_earnings_inkind_gig_cf ia5_total_income ia5_total_income_zero total_income 
	
	
	
	/**************************************************************************
	* REGULAR EMPLOYMENT INCOME (IA3) – CASH / IN-KIND / TOTAL
	**************************************************************************/

	* Cash: IA3_A + IA3_B
	egen regular_cash_income_tmp = rowtotal(ia3_a ia3_b)
	gen  regular_cash_income     = . 
	replace regular_cash_income  = regular_cash_income_tmp if ia2 == 1
	replace regular_cash_income  = . if ia2 != 1

	drop regular_cash_income_tmp

	la var regular_cash_income "Cash income from regular employment (IA3_A + IA3_B)"

		as regular_cash_income >= 0 if ia2 == 1 & regular_cash_income < .
		as regular_cash_income == . if ia2 != 1


	* In-kind: IA3_C + IA3_D + IA3_E + IA3_F
	egen regular_inkind_income_tmp = rowtotal(ia3_c ia3_d ia3_e ia3_f)
	gen  regular_inkind_income     = .
	replace regular_inkind_income  = regular_inkind_income_tmp if ia2 == 1
	replace regular_inkind_income  = . if ia2 != 1

	drop regular_inkind_income_tmp

	la var regular_inkind_income "In-kind income from regular employment (IA3_C–IA3_F)"

		as regular_inkind_income >= 0 if ia2 == 1 & regular_inkind_income < .
		as regular_inkind_income == . if ia2 != 1


	* Total regular = cash + in-kind
	egen total_regular_income_tmp = rowtotal(regular_cash_income regular_inkind_income)
	gen  total_regular_income     = .
	replace total_regular_income  = total_regular_income_tmp if ia2 == 1
	replace total_regular_income  = . if ia2 != 1

	drop total_regular_income_tmp

	la var total_regular_income "Total regular employment income (cash + in-kind)"

		as total_regular_income >= 0 if ia2 == 1 & total_regular_income < .
		as total_regular_income == . if ia2 != 1

		
	/**************************************************************************
	* SEASONAL / GIG EMPLOYMENT INCOME (IA6) – CASH / IN-KIND / TOTAL
	**************************************************************************/

	* Cash: IA6_A + IA6_B
	egen season_cash_income_tmp = rowtotal(ia6_a ia6_b)
	gen  season_cash_income     = .
	replace season_cash_income  = season_cash_income_tmp if ia5 == 1
	replace season_cash_income  = . if ia5 != 1

	drop season_cash_income_tmp

	la var season_cash_income "Cash income from seasonal/gig work (IA6_A + IA6_B)"

		as season_cash_income >= 0 if ia5 == 1 & season_cash_income < .
		as season_cash_income == . if ia5 != 1


	* In-kind: IA6_C + IA6_D + IA6_E + IA6_F
	egen season_inkind_income_tmp = rowtotal(ia6_c ia6_d ia6_e ia6_f)
	gen  season_inkind_income     = .
	replace season_inkind_income  = season_inkind_income_tmp if ia5 == 1
	replace season_inkind_income  = . if ia5 != 1

	drop season_inkind_income_tmp

	la var season_inkind_income "In-kind income from seasonal/gig work (IA6_C–IA6_F)"

		as season_inkind_income >= 0 if ia5 == 1 & season_inkind_income < .
		as season_inkind_income == . if ia5 != 1


	* Total seasonal/gig
	egen total_season_income_tmp = rowtotal(season_cash_income season_inkind_income)
	gen  total_season_income     = .
	replace total_season_income  = total_season_income_tmp if ia5 == 1
	replace total_season_income  = . if ia5 != 1

	drop total_season_income_tmp

	la var total_season_income "Total seasonal/gig income (cash + in-kind)"

		as total_season_income >= 0 if ia5 == 1 & total_season_income < .
		as total_season_income == . if ia5 != 1

		
	
		
	/**************************************************************************
	* TOTAL INCOME = REGULAR + SEASONAL/GIG
	**************************************************************************/

	egen total_income_tmp = rowtotal(total_regular_income total_season_income)
	gen  total_income     = total_income_tmp
	drop total_income_tmp

	la var total_income "Total income from employment (regular + seasonal/gig)"

		as total_income >= 0 if (ia2 == 1 | ia5 == 1) & total_income < .
		
		
		
	replace total_income = . if total_income == 0	
	
	
		
	}
	

	
	
	/// RENAME AND RELABEL

	
	
	
	
	

	/// CONSISTENT WITH BASELINE 

	
	
	
	
	
	
	/// STATUS FOR NEW MEMBER 
	
	cap drop if hhid == 89012
	
	la lang ${LNG}
	save "$zzz/income_trailer.dta", replace
	
}
*------------------------------------------------------------------------------*
	
	
{ 
	///MERGE 
	use "$zzz/income_trailer.dta", clear

	merge m:1 hhid using "$raw/${dta_file}_${date}_M00_passport.dta", ///
		keepusing(dur_inc round)

	tab _merge
	keep if _merge == 3
	drop _merge
	
	drop fmida27 income_fmidage sid koboid uuid
	
	drop round income_fmida1
	order hhid fmid, first
	order dur_inc subm_date subm_time, last
	
	compress 
	save "${raw}/income_trailer.dta", replace
}

	

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	